id: devops-oncall
name: DevOps On-Call
description: A focused set of prompts, instructions, and a chat mode to help triage incidents and respond quickly with DevOps tools and Azure resources.
license: "GPL-3.0"
tags: [devops, incident-response, oncall, azure]
items:
  - path: .github/instructions/containerization-docker-best-practices.instructions.md
    kind: instruction
  - path: .github/prompts/multi-stage-dockerfile.prompts.md
    kind: prompt
display:
  ordering: manual
  show_badge: true
