id: frontend-web-dev
name: Frontend Web Development
description: Essential prompts, instructions, and chat modes for modern frontend web development including React, Angular, Vue, TypeScript, and CSS frameworks.
license: "GPL-3.0"
tags: [frontend, web, react, typescript, javascript, css, html, angular, vue]
items:
  # Development Instructions
  - path: .github/instructions/nodejs-javascript-vitest.instructions.md
    kind: instruction

  # Prompts
  - path: .github/prompts/playwright-explore-website.prompts.md
    kind: prompt
  - path: .github/prompts/playwright-generate-test.prompts.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true
