id: project-planning
name: Project Planning & Management
description: Tools and guidance for software project planning, feature breakdown, epic management, implementation planning, and task organization for development teams.
license: "GPL-3.0"
tags: [planning, project-management, epic, feature, implementation, task, architecture, technical-spike]
items:
  # Planning Chat Modes
  - path: .github/chatmodes/task-planner.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/task-researcher.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/planner.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/plan.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/implementation-plan.chatmodes.md
    kind: chat-mode

  # Planning Instructions
  - path: .github/instructions/task-implementation.instructions.md
    kind: instruction
  - path: .github/instructions/spec-driven-workflow-v1.instructions.md
    kind: instruction

  # Planning Prompts
  - path: .github/prompts/breakdown-feature-implementation.prompts.md
    kind: prompt
  - path: .github/prompts/breakdown-feature-prd.prompts.md
    kind: prompt
  - path: .github/prompts/breakdown-epic-arch.prompts.md
    kind: prompt
  - path: .github/prompts/breakdown-epic-pm.prompts.md
    kind: prompt
  - path: .github/prompts/create-implementation-plan.prompts.md
    kind: prompt
  - path: .github/prompts/update-implementation-plan.prompts.md
    kind: prompt
  - path: .github/prompts/create-github-issues-feature-from-implementation-plan.prompts.md
    kind: prompt
  - path: .github/prompts/create-technical-spike.prompts.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true
