id: testing-automation
name: Testing & Test Automation
description: Comprehensive collection for writing tests, test automation, and test-driven development including unit tests, integration tests, and end-to-end testing strategies.
license: "GPL-3.0"
tags: [testing, tdd, automation, unit-tests, integration, playwright, jest, nunit]
items:
  # TDD Chat Modes
  - path: .github/chatmodes/tdd-red.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/tdd-green.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/tdd-refactor.chatmodes.md
    kind: chat-mode
  - path: .github/chatmodes/playwright-tester.chatmodes.md
    kind: chat-mode

  # Testing Instructions
  - path: .github/instructions/playwright-typescript.instructions.md
    kind: instruction

  # Testing Prompts
  - path: .github/prompts/playwright-explore-website.prompts.md
    kind: prompt
  - path: .github/prompts/playwright-generate-test.prompts.md
    kind: prompt
  - path: .github/prompts/ai-prompt-engineering-safety-review.prompts.md
    kind: prompt

display:
  ordering: alpha
  show_badge: true
